In [43]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

dataset = pd.read_table('Data/data_banknote_authentication.txt', sep = ",", header=None)
X = dataset.iloc[:, :-1].values
t = dataset.iloc[:, -1].values

# split the training set, validation set and test set of ratio 6:2:2
X_train, X_test, t_train, t_test = train_test_split(X, t, test_size=0.2, random_state=8775)
X_train, X_valid, t_train, t_valid = train_test_split(X_train, t_train, test_size=0.25, random_state=8775)

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)
X_valid = sc.transform(X_valid)
print(X_train)

[[-0.8262679  -1.54205887  0.96866858  0.57237498]
 [-0.5859893  -0.11357767  1.49099905  0.85091245]
 [-0.21690679 -0.23431156 -0.4007196   0.5154012 ]
 ...
 [ 1.10865039  0.18643168 -0.13995204  0.82053048]
 [-1.02129319 -0.41612509  0.08534552  0.33371887]
 [ 0.54620116 -0.0257496  -1.00242774  0.64707517]]


In [44]:
clf = MLPClassifier( activation='relu', 
                    solver='sgd', 
                    learning_rate='constant', 
                    learning_rate_init=0.05,
                    hidden_layer_sizes=(5, 2), 
                    n_iter_no_change=100,
                    early_stopping=True)

def NNClassifier(input, hidden_layer_sizes,epochs, learning_rate):
    layer_1_size = hidden_layer_sizes[0]
    layer_2_size = hidden_layer_sizes[1]

    input = np.insert(input,0,1)     # add dummy one
    w_1 = np.ones((layer_1_size, 5))
    z_1 = np.dot(w_1, input.T)
    h_1 = ReLU(z_1)

    h_1 = np.insert(h_1,0,1)
    w_2 = np.ones((layer_2_size, layer_1_size+1))
    z_2 = np.dot(w_2, h_1.T)
    h_2 = ReLU(z_2)

    h_2 = np.insert(h_2,0,1)
    w_3 = np.ones((1, layer_2_size+1))
    z_3 = np.dot(w_3, h_2.T)
    output = np.power((1 + np.exp(-z_3)), -1)

    return output


def ReLU(matrix):
    for element in matrix:
        if (element<0):
            element=0
    return matrix

inp=np.asarray([1,-2,-4,-5])
o=NNClassifier(inp,hidden_layer_sizes=(2,2),epochs=0,learning_rate=0)

print(o)



[4.65888615e-15]
